require("modules.lsp.php")
require("modules.lsp.html")
require("modules.lsp.css")
require("modules.lsp.tailwind")
require("modules.lsp.typescript")
require("modules.lsp.go")
require("modules.lsp.rust")
require("modules.lsp.sql")

require("modules.lsp.json")
require("modules.lsp.yaml")
