[theme]
name = "nord-dark"
[theme.overrides]
idle_bg = "#282A36"
idle_fg = "#F8F8F2"
info_bg = "#82aaff"
info_fg = "#292d3e"
good_bg = "#69FF94"
good_fg = "#282A36"
warning_bg = "#FFB86C"
warning_fg = "#282A36"
critical_bg = "#FF6E6E"
critical_fg = "#282A36"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"

[icons]
name = "awesome"
[icons.overrides]
music = ""

[[block]]
block = "focused_window"
max_width = 30
show_marks = "visible"

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]
on_collapsed_click = "spotify"
hide_when_empty = true
marquee = false
max_width = 30
dynamic_width = true
[block.theme_overrides]
info_bg = "#1DB954"
info_fg = "#191414"
idle_bg = "#282A36"
idle_fg = "#F8F8F2"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
[block.theme_overrides]
idle_bg = "#4B5263"
idle_fg = "#ffffff"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
[block.theme_overrides]
idle_bg = "#3E4452"
idle_fg = "#FFFFFF"

[[block]]
block = "cpu"
interval = 1
info = 40
warning = 60
critical = 90
[block.theme_overrides]
idle_bg = "#3B4048"
idle_fg = "#ffffff"

#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

[[block]]
block = "sound"
[block.theme_overrides]
idle_bg = "#44475A"
idle_fg = "#ffffff"
warning_bg = "#FFB86C"
warning_fg = "#FFFFFF"

[[block]]
block = "battery"
driver = "upower"
interval = 10
format = "{percentage} {time}"
good = 90
info = 60
warning = 30
critical = 10
[block.theme_overrides]
good_bg = "#69FF94"
idle_bg = "#A4FFFF"
info_bg = "#82aaff"
warning_bg = "#FFB86C"
critical_bg = "#FF6E6E"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
on_click = "if pgrep zenity; then pkill zenity; fi; zenity --calendar"
